# Site wide configuration

title: Ecology & Evolution @ OIST <br> Evolutionary Genomics @ ANU
locale:           en-US
url: https://mikheyevlab.github.io
baseurl: /EcoEvoUnit

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      share: true

paginate: 5 # amount of posts to show on home page
paginate_path: /page:num/

# Site owner
owner:
  name: Mikheyev Labs
  avatar: logo.png
  bio: This is a joint website for the Ecology and Evolution Unit at the Okinawa Institute of Science and Technology and the Evolutionary Genomics Lab at the Auntralian National University
  email: ecoevo@oist.jp
  disqus-shortname: 
  twitter: #username
  google:
    analytics: UA-45186360-8

  github: MikheyevLab
  stackoverflow: #http://stackoverflow.com/users/123456/username

remote_theme: "mmistakes/minimal-mistakes"
