# Site wide configuration

title:            Ecology and Evolution Unit
locale:           en-JP
# baseurl:  /site
# url: http://ecoevo.unit.oist.jp/site

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Eco Evo Lab
  avatar: logo.png
  bio: "Better living through sequencing chemistry"
  email: ecoevo@oist.jp
  disqus-shortname: 
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-45186360-8
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: MikheyevLab
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

remote_theme: minimal-mistakes-jekyll
