# Site wide configuration

title: Mikheyev Labs
locale:           en-US
url: https://mikheyevlab.github.io
baseurl: /EcoEvoUnit

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
 
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: # true
      share: true
      related: true

paginate: 5 # amount of posts to show on home page
paginate_path: /page:num/

analytics:
  provider: "google"
  google:
    tracking_id: "UA-45186360-8"

# Site owner
owner:
  name: Mikheyev Labs
  avatar: logo.png
  bio: This is a joint website for the Ecology and Evolution Unit at the Okinawa Institute of Science and Technology and the Evolutionary Genomics Lab at the Auntralian National University
  email: ecoevo@oist.jp
  disqus-shortname: 
  twitter: #username
  github: MikheyevLab
  stackoverflow: #http://stackoverflow.com/users/123456/username

remote_theme: "mmistakes/minimal-mistakes@fbb7356d74995fb874258cfc37e74b31bd1b318b"